cmake_minimum_required(VERSION 3.15)

include(ExternalProject)

set(OPENSSL_VERSION "openssl-1.1.1v")
set(OPENSSL_ROOT ${CMAKE_CURRENT_BINARY_DIR}/${OPENSSL_VERSION})
set(OPENSSL_SOURCE_PATH "${OPENSSL_ROOT}/src/${OPENSSL_VERSION}")
set(OPENSSL_URL ${CMAKE_SOURCE_DIR}/module/local/${OPENSSL_VERSION}.tar.gz)
set(OPENSSL_CONFIGURE_COMMAND ${OPENSSL_SOURCE_PATH}/config --prefix=/usr/local)
set(OPENSSL_MAKE_COMMAND /usr/bin/make -j 16)
set(OPENSSL_INSTALL_COMMAND /usr/bin/make install)

ExternalProject_Add(
        ${OPENSSL_VERSION}
        URL ${OPENSSL_URL}
        PREFIX ${OPENSSL_ROOT}
        CONFIGURE_COMMAND ${OPENSSL_CONFIGURE_COMMAND}
        BUILD_COMMAND ${OPENSSL_MAKE_COMMAND}
        INSTALL_COMMAND ${OPENSSL_INSTALL_COMMAND}
)
